Repository Netcracker/qubership-logging-operator, pull requests merged in 2025-04, with the labels that each got.

#49 feat[skip ci]: Add Docker configuration and workflows for building and releasing the Logging Operator
  .github/assets-config.yml
  .github/dev-metadata-config.yml
  .github/docker-dev-config.json
  .github/docker-release-config.json
  .github/workflows/docker-dev.yml
  .github/workflows/docker-release.yml
  .github/workflows/docker_dev.yml
Labels: enhancement

#52 ci: fix dev build workflow
  .github/dev-metadata-config.yml
Labels: bug

#54 fix: update Docker release configuration and workflow for tag handling
  .github/docker-release-config.json
  .github/workflows/docker-release.yml
Labels: bug

#64 fix: change incorrect ruby code in FluentD filters
  controllers/fluentd/fluentd.configmap/conf.d/filters/filter-k8s-audit.conf
Labels: bug

#65 chore(deps): update default images
  charts/qubership-logging-operator/templates/_helpers.tpl
  docs/installation.md
Labels: dependencies

#66 chore(deps): update go.work.sum and other .sum files
  api/go.mod
  api/go.sum
  go.work.sum
Labels: dependencies

#73 fix: fix version of qubership-docker-integration-tests
  test/robot-tests/Dockerfile
Labels: bug
