Repository Netcracker/qubership-logging-operator, pull requests merged in 2025-05, with the labels that each got.

#78 fix: bump fluentbit image
  charts/qubership-logging-operator/templates/_helpers.tpl
Labels: bug

#61 Add workflow for cleaning up old Docker images
  .github/workflows/cleanup-old-docker-container.yml
Labels: enhancement

#87 refactor: Refactor Docker build workflow and fix metadata action reference
  .github/dev-metadata-config.yml
  .github/workflows/docker-dev.yml
Labels: bug, refactor
